idioma : java
jdk :
  - openjdk8

script : ./mvnw instalación limpia


trabajos :
  incluyen :
    - etapa : prueba
      script : ./mvnw prueba limpia

notificación :
  correo electrónico : leonardoguillen946@gmail.com
